/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRoleRouteImport } from './routes/register.$role'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoleRoute = RegisterRoleRouteImport.update({
  id: '/register/$role',
  path: '/register/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/register/$role': typeof RegisterRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/register/$role': typeof RegisterRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/register/$role': typeof RegisterRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/get-started' | '/login' | '/register/$role'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/get-started' | '/login' | '/register/$role'
  id: '__root__' | '/' | '/get-started' | '/login' | '/register/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  RegisterRoleRoute: typeof RegisterRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$role': {
      id: '/register/$role'
      path: '/register/$role'
      fullPath: '/register/$role'
      preLoaderRoute: typeof RegisterRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  RegisterRoleRoute: RegisterRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
