-- Correct the live directory to the 96 degree-granting institutions in
-- uniRank's 2026 Myanmar directory, while preserving the existing real
-- University of Information Technology row whose official site confirms its
-- degree programmes. An earlier draft imported the broader Wikipedia list,
-- which also contains institutions outside the agreed scope.
--
-- This migration is intentionally separate from the canonical seed migration:
-- fresh databases get only the 96 rows from 20260829120000, while databases
-- that received the broader draft are brought back to the same state without
-- deleting rows that posts or profiles may reference.

with missing(
  slug, name, short_name, university_type, city, region, founded_year, description
) as (
  values
    ('naypyitaw-technological-university', 'Naypyitaw Technological University', 'NPTTU', 'public', 'Naypyidaw', 'Nay Pyi Taw Union Territory', 2007::smallint,
     'Public technological university in Naypyidaw awarding undergraduate engineering and technology degrees.'),
    ('technological-university-mandalay', 'Technological University, Mandalay', 'TU Mandalay', 'public', 'Patheingyi', 'Mandalay Region', null,
     'Public technological university in the Mandalay Region awarding undergraduate engineering degrees.'),
    ('technological-university-yamethin', 'Technological University, Yamethin', 'TU Yamethin', 'public', 'Yamethin', 'Mandalay Region', null,
     'Public technological university in Yamethin awarding undergraduate engineering degrees.'),
    ('university-of-myitkyina', 'University of Myitkyina', 'UMK', 'public', 'Myitkyina', 'Kachin State', null,
     'Public arts and science university in Myitkyina offering undergraduate degrees in the humanities and sciences.'),
    ('university-of-pyay', 'University of Pyay', 'UPY', 'public', 'Pyay', 'Bago Region', null,
     'Public arts and science university in Pyay offering undergraduate degrees in the humanities and sciences.')
)
insert into public.universities (
  slug, name, short_name, university_type, city, region, country_code,
  founded_year, description, is_published, data_source_url
)
select
  slug,
  name,
  short_name,
  university_type::public.university_type,
  city,
  region,
  'MM',
  founded_year,
  description,
  true,
  'https://www.unirank.org/mm/a-z/'
from missing
on conflict (slug) do update set
  region = coalesce(public.universities.region, excluded.region),
  founded_year = coalesce(public.universities.founded_year, excluded.founded_year),
  data_source_url = excluded.data_source_url,
  is_published = true,
  archived_at = null,
  updated_at = now();

with eligible(slug) as (
  values
    ('bago-university'),
    ('bhamo-university'),
    ('dagon-university'),
    ('dawei-university'),
    ('university-of-east-yangon'),
    ('hinthada-university'),
    ('hpa-an-university'),
    ('university-of-kalay'),
    ('kyaingtong-university'),
    ('technological-university-kyaukse'),
    ('kyaukse-university'),
    ('lashio-university'),
    ('loikaw-university'),
    ('magway-university'),
    ('mandalay-technological-university'),
    ('mandalay-university'),
    ('university-of-foreign-languages-mandalay'),
    ('maubin-university'),
    ('mawlamyine-university'),
    ('meiktila-university'),
    ('meiktila-university-of-economics'),
    ('monywa-university'),
    ('monywa-university-of-economics'),
    ('myanmar-aerospace-engineering-university'),
    ('myanmar-maritime-university'),
    ('myeik-university'),
    ('national-university-of-arts-and-culture-mandalay'),
    ('national-university-of-arts-and-culture-yangon'),
    ('naypyitaw-technological-university'),
    ('pakokku-university'),
    ('panglong-university'),
    ('pathein-university'),
    ('polytechnic-university-dawei'),
    ('polytechnic-university-myeik'),
    ('pyay-technological-university'),
    ('sagaing-university'),
    ('sagaing-university-of-education'),
    ('shwebo-university'),
    ('sittway-university'),
    ('taunggyi-university'),
    ('taungoo-university'),
    ('technological-university-thanlyin'),
    ('technological-university-bhamo'),
    ('technological-university-hinthada'),
    ('technological-university-hmawbi'),
    ('technological-university-hpa-an'),
    ('technological-university-kalay'),
    ('technological-university-kyaingtong'),
    ('technological-university-lashio'),
    ('technological-university-loikaw'),
    ('technological-university-magway'),
    ('technological-university-mandalay'),
    ('technological-university-maubin'),
    ('technological-university-mawlamyine'),
    ('technological-university-meiktila'),
    ('technological-university-monywa'),
    ('technological-university-myitkyina'),
    ('technological-university-pakokku'),
    ('technological-university-panglong'),
    ('technological-university-pathein'),
    ('technological-university-sagaing'),
    ('technological-university-sittwe'),
    ('technological-university-taunggyi'),
    ('technological-university-taungoo'),
    ('technological-university-yamethin'),
    ('university-of-community-health-magway'),
    ('university-of-computer-studies-mandalay'),
    ('university-of-computer-studies-yangon'),
    ('university-of-dental-medicine-mandalay'),
    ('university-of-dental-medicine-yangon'),
    ('university-of-forestry-and-environmental-science-yezin'),
    ('university-of-medical-technology-mandalay'),
    ('university-of-medical-technology-yangon'),
    ('university-of-medicine-1-yangon'),
    ('university-of-medicine-2-yangon'),
    ('university-of-medicine-magway'),
    ('university-of-medicine-mandalay'),
    ('university-of-medicine-taunggyi'),
    ('university-of-myitkyina'),
    ('university-of-nursing-mandalay'),
    ('university-of-nursing-yangon'),
    ('university-of-pharmacy-mandalay'),
    ('university-of-pharmacy-yangon'),
    ('university-of-public-health-yangon'),
    ('university-of-pyay'),
    ('university-of-technology-yadanabon-cyber-city'),
    ('university-of-veterinary-science-yezin'),
    ('university-of-west-yangon'),
    ('west-yangon-technological-university'),
    ('yadanabon-university'),
    ('yangon-technological-university'),
    ('university-of-yangon'),
    ('yangon-university-of-economics'),
    ('yangon-university-of-education'),
    ('university-of-foreign-languages-yangon'),
    ('yezin-agricultural-university')
)
update public.universities u
set is_published = false,
    archived_at = coalesce(u.archived_at, now()),
    updated_at = now()
where u.data_source_url = 'https://en.wikipedia.org/wiki/List_of_universities_in_Myanmar'
  and not exists (select 1 from eligible e where e.slug = u.slug);

with eligible(slug) as (
  values
    ('bago-university'), ('bhamo-university'), ('dagon-university'),
    ('dawei-university'), ('university-of-east-yangon'), ('hinthada-university'),
    ('hpa-an-university'), ('university-of-kalay'), ('kyaingtong-university'),
    ('technological-university-kyaukse'), ('kyaukse-university'),
    ('lashio-university'), ('loikaw-university'), ('magway-university'),
    ('mandalay-technological-university'), ('mandalay-university'),
    ('university-of-foreign-languages-mandalay'), ('maubin-university'),
    ('mawlamyine-university'), ('meiktila-university'),
    ('meiktila-university-of-economics'), ('monywa-university'),
    ('monywa-university-of-economics'),
    ('myanmar-aerospace-engineering-university'), ('myanmar-maritime-university'),
    ('myeik-university'), ('national-university-of-arts-and-culture-mandalay'),
    ('national-university-of-arts-and-culture-yangon'),
    ('naypyitaw-technological-university'), ('pakokku-university'),
    ('panglong-university'), ('pathein-university'),
    ('polytechnic-university-dawei'), ('polytechnic-university-myeik'),
    ('pyay-technological-university'), ('sagaing-university'),
    ('sagaing-university-of-education'), ('shwebo-university'),
    ('sittway-university'), ('taunggyi-university'), ('taungoo-university'),
    ('technological-university-thanlyin'), ('technological-university-bhamo'),
    ('technological-university-hinthada'), ('technological-university-hmawbi'),
    ('technological-university-hpa-an'), ('technological-university-kalay'),
    ('technological-university-kyaingtong'), ('technological-university-lashio'),
    ('technological-university-loikaw'), ('technological-university-magway'),
    ('technological-university-mandalay'), ('technological-university-maubin'),
    ('technological-university-mawlamyine'), ('technological-university-meiktila'),
    ('technological-university-monywa'), ('technological-university-myitkyina'),
    ('technological-university-pakokku'), ('technological-university-panglong'),
    ('technological-university-pathein'), ('technological-university-sagaing'),
    ('technological-university-sittwe'), ('technological-university-taunggyi'),
    ('technological-university-taungoo'), ('technological-university-yamethin'),
    ('university-of-community-health-magway'),
    ('university-of-computer-studies-mandalay'),
    ('university-of-computer-studies-yangon'),
    ('university-of-dental-medicine-mandalay'),
    ('university-of-dental-medicine-yangon'),
    ('university-of-forestry-and-environmental-science-yezin'),
    ('university-of-medical-technology-mandalay'),
    ('university-of-medical-technology-yangon'),
    ('university-of-medicine-1-yangon'), ('university-of-medicine-2-yangon'),
    ('university-of-medicine-magway'), ('university-of-medicine-mandalay'),
    ('university-of-medicine-taunggyi'), ('university-of-myitkyina'),
    ('university-of-nursing-mandalay'), ('university-of-nursing-yangon'),
    ('university-of-pharmacy-mandalay'), ('university-of-pharmacy-yangon'),
    ('university-of-public-health-yangon'), ('university-of-pyay'),
    ('university-of-technology-yadanabon-cyber-city'),
    ('university-of-veterinary-science-yezin'), ('university-of-west-yangon'),
    ('west-yangon-technological-university'), ('yadanabon-university'),
    ('yangon-technological-university'), ('university-of-yangon'),
    ('yangon-university-of-economics'), ('yangon-university-of-education'),
    ('university-of-foreign-languages-yangon'), ('yezin-agricultural-university')
)
update public.universities u
set data_source_url = 'https://www.unirank.org/mm/a-z/',
    is_published = true,
    archived_at = null,
    updated_at = now()
where exists (select 1 from eligible e where e.slug = u.slug);
