-- Student-curated university cover photos bundled with the frontend under
-- public/university-photos. These paths are public app assets rather than
-- Supabase Storage objects, so the frontend serves them directly.

with photo(slug, path, credit, licence) as (
  values
    ('bago-university', '/university-photos/BagoUni.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('dawei-university', '/university-photos/DaweiUni.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('hakha-university', '/university-photos/Hakha%20Uni.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('hinthada-university', '/university-photos/Hinthada%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('kyaingtong-university', '/university-photos/Kyaing%20Tong%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('kyaukse-university', '/university-photos/Kyaukse%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('mandalar-university', '/university-photos/Mandalar%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('maubin-university', '/university-photos/Maubin%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('monywa-university-of-economics', '/university-photos/Monywa%20University%20of%20Economics.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('monywa-university', '/university-photos/Monywa%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('myanmar-aerospace-engineering-university', '/university-photos/Myanmar%20Aerospace%20Engineering%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('myanmar-institute-of-information-technology', '/university-photos/Myanmar%20Institute%20of%20Information%20Technology.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('myeik-university', '/university-photos/Myeik%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('myingyan-university', '/university-photos/Myingyan%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('naypyitaw-technological-university', '/university-photos/Naypyitaw%20Technological%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('national-university-of-arts-and-culture-mandalay', '/university-photos/NUAC%20Mandalay.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('polytechnic-university-dawei', '/university-photos/Polytechnic%20University%2C%20Dawei.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('polytechnic-university-myeik', '/university-photos/Polytechnic%20University(Myeik).jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('sagaing-university-of-education', '/university-photos/Sagaing%20University%20of%20Education.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('sagaing-university', '/university-photos/Sagaing%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('taungup-university', '/university-photos/Taungup%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-bhamo', '/university-photos/Technological%20University%20Bhamo.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-kalay', '/university-photos/Technological%20University%20Kalay.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-kyaingtong', '/university-photos/Technological%20University%20Kyaingtong.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-lashio', '/university-photos/Technological%20University%20Lashio.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-loikaw', '/university-photos/Technological%20University%20Loikaw.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-mandalay', '/university-photos/Technological%20University%20Mandalay.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-maubin', '/university-photos/Technological%20University%20Maubin.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-mawlamyine', '/university-photos/Technological%20University%20Mawlamyine.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-hinthada', '/university-photos/Technological%20University%2C%20Hinthada.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-kyaukse', '/university-photos/Technological%20University%2C%20Kyaukse.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('technological-university-magway', '/university-photos/Technological%20University%2C%20Magway.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-kalay', '/university-photos/University%20of%20Computer%20Studies%2C%20Kalay.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-lashio', '/university-photos/University%20of%20Computer%20Studies%2C%20Lashio.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-loikaw', '/university-photos/University%20of%20Computer%20Studies%2C%20Loikaw.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-magway', '/university-photos/university%20of%20computer%20studies%2C%20magway.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-mandalay', '/university-photos/University%20of%20Computer%20Studies%2C%20Mandalay.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-maubin', '/university-photos/University%20of%20Computer%20Studies%2C%20Maubin.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-meiktila', '/university-photos/University%20of%20Computer%20Studies%2C%20Meiktila.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-monywa', '/university-photos/University%20of%20Computer%20Studies%2C%20Monywa.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-myeik', '/university-photos/University%20of%20Computer%20Studies%2C%20Myeik.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-myitkyina', '/university-photos/University%20of%20Computer%20Studies%2C%20Myitkyina.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-pakokku', '/university-photos/University%20of%20Computer%20Studies%2C%20Pakokku.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-panglong', '/university-photos/University%20of%20Computer%20Studies%2C%20Panglong.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-pathein', '/university-photos/University%20of%20Computer%20Studies%2C%20Pathein.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-pyay', '/university-photos/University%20of%20Computer%20Studies%2C%20Pyay.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-sittwe', '/university-photos/University%20of%20Computer%20Studies%2C%20Sittwe.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-taungoo', '/university-photos/University%20of%20Computer%20Studies%2C%20Taungoo.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-computer-studies-thaton', '/university-photos/University%20of%20Computer%20Studies%2C%20Thaton.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-dental-medicine-yangon', '/university-photos/University%20of%20Dental%20Medicine%2C%20Yangon.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-distance-education-mandalay', '/university-photos/University%20of%20Distance%20Education%2C%20Mandalay.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-distance-education-yangon', '/university-photos/University%20of%20Distance%20Education%2C%20Yangon.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-east-yangon', '/university-photos/University%20of%20East%20Yangon.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-forestry-and-environmental-science-yezin', '/university-photos/University%20of%20Forestry%20and%20Environmental%20Science%2C%20Yezin.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-information-technology', '/university-photos/University%20of%20Information%20Technology.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-kalay', '/university-photos/University%20of%20Kalay.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-pharmacy-yangon', '/university-photos/University%20of%20Pharmacy%2C%20Yangon.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-veterinary-science-yezin', '/university-photos/University%20of%20Veterinary%20Science%2C%20Yezin.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('university-of-west-yangon', '/university-photos/University%20of%20West%20Yangon.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set'),
    ('west-yangon-technological-university', '/university-photos/West%20Yangon%20Technological%20University.jpg', 'TAKKA curated campus photo', 'Student-curated Telegram university photo set')
)
update public.universities u
set cover_image_path = photo.path,
    cover_image_credit = photo.credit,
    cover_image_source_url = null,
    cover_image_license = photo.licence,
    updated_at = now()
from photo
where u.slug = photo.slug;
