-- Enrich the university directory from the user-maintained workbook
-- "Major universities in Myanmar.xlsx" received on 2026-09-01.
--
-- The workbook is treated as collected catalog data. Existing canonical names,
-- slugs, and stronger official-source descriptions remain authoritative.

with collected(slug, founded_year, website_url, about) as (
  values
    ('university-of-yangon', 1920::smallint, 'https://uy.edu.mm', 'Myanmar''s oldest and most renowned university, with arts, sciences, law, and multidisciplinary study on its Inya Lake campus.'),
    ('yangon-technological-university', 1924::smallint, 'https://ytu.edu.mm', 'Premier public engineering and technology university in Insein, with origins in the engineering department of Rangoon University.'),
    ('university-of-computer-studies-yangon', 1988::smallint, 'https://ucsy.edu.mm', 'Leading public university for computer science, computer technology, and information technology in Yangon.'),
    ('yangon-university-of-economics', 1964::smallint, 'https://yueco.edu.mm', 'Public economics and business university training economists, statisticians, accountants, administrators, and managers across three Yangon campuses.'),
    ('dagon-university', 1993::smallint, 'https://dagonuniversity.edu.mm', 'Large public arts and sciences university in North Dagon, Yangon.'),
    ('university-of-east-yangon', 2000::smallint, 'https://eyu.edu.mm', 'Public arts and sciences university in Thanlyin, southeast of Yangon.'),
    ('university-of-medicine-1-yangon', 1930::smallint, 'https://um1yangon.edu.mm', 'Myanmar''s oldest medical school, based in Latha Township, Yangon.'),
    ('university-of-medicine-2-yangon', 1963::smallint, 'https://um2ygn.edu.mm', 'Public medical university in North Okkalapa offering undergraduate and postgraduate medical education.'),
    ('university-of-dental-medicine-yangon', 1964::smallint, 'https://udmyangon-edu.com', 'Public university for dental education in Thingangyun, Yangon.'),
    ('university-of-nursing-yangon', 1986::smallint, 'https://uonygn.gov.mm', 'Public nursing university in Lanmadaw offering undergraduate, postgraduate, bridge, and specialist diploma study.'),
    ('university-of-pharmacy-yangon', null::smallint, 'https://uopygn.gov.mm', 'Public pharmacy university in Yangon offering undergraduate and postgraduate pharmacy education.'),
    ('university-of-public-health-yangon', 2007::smallint, 'https://uph-myanmar.gov.mm', 'Public university in Latha focused on graduate and postgraduate education in public health.'),
    ('university-of-foreign-languages-yangon', 1964::smallint, 'https://yufl.edu.mm', 'Public foreign-languages university teaching Asian and European languages, Myanmar, and linguistics.'),
    ('yangon-university-of-education', null::smallint, 'https://lms.yuoe.edu.mm', 'Public teacher-education university on Pyay Road, Yangon.'),
    ('university-of-information-technology', 2012::smallint, 'https://uit.edu.mm', 'Public centre of excellence for information and communication technology on the Hlaing Campus.'),
    ('myanmar-maritime-university', 2002::smallint, 'https://mmu.edu.mm', 'Public maritime engineering university at Thilawa in Thanlyin.'),
    ('myanmar-aerospace-engineering-university', 2002::smallint, 'https://maeu.edu.mm', 'Specialized public aerospace engineering university in Meiktila.'),
    ('national-university-of-arts-and-culture-yangon', 1993::smallint, 'https://culture.gov.mm', 'Public university in South Dagon for Myanmar performing arts, visual arts, and cultural study.'),
    ('technological-university-thanlyin', 2007::smallint, 'https://tuthanlyin.edu.mm', 'Public engineering university in Thanlyin, Yangon Region.'),
    ('university-of-west-yangon', 2002::smallint, 'https://wyu.edu.mm', 'Public liberal arts and sciences university in Htantabin, Yangon Region.'),
    ('mandalay-university', 1925::smallint, 'https://mu.edu.mm', 'Myanmar''s second-oldest university and a major centre for arts, sciences, and law in Upper Myanmar.'),
    ('mandalay-technological-university', 1991::smallint, 'https://mtu.edu.mm', 'Senior public engineering university in Patheingyi offering engineering, architecture, and biotechnology study.'),
    ('university-of-computer-studies-mandalay', 1997::smallint, 'https://ucsm.edu.mm', 'Upper Myanmar''s first specialized computer university, based in Patheingyi.'),
    ('university-of-foreign-languages-mandalay', 1997::smallint, 'https://mufl.edu.mm', 'Public foreign-languages university in Aungmyethazan, Mandalay.'),
    ('yadanabon-university', 2000::smallint, 'https://ydbu.edu.mm', 'Large public arts and sciences university in Amarapura, Mandalay Region.'),
    ('university-of-medicine-mandalay', 1954::smallint, 'https://ummdy.edu.mm', 'Public medical university in central Mandalay offering undergraduate and postgraduate medical education.'),
    ('university-of-dental-medicine-mandalay', 1998::smallint, 'https://udmmandalay.edu.mm', 'Public dental university and teaching hospital in Mandalay.'),
    ('university-of-pharmacy-mandalay', null::smallint, 'https://uopmdy.gov.mm', 'Public pharmacy university in Mandalay offering undergraduate and postgraduate pharmacy education.'),
    ('university-of-nursing-mandalay', 1998::smallint, 'https://uonmdy.edu.mm', 'Public nursing university in Chanmyathazi, Mandalay.'),
    ('university-of-traditional-medicine-mandalay', null::smallint, 'https://utm.edu.mm', 'Public university in Mandalay dedicated to Myanmar traditional medicine.'),
    ('national-university-of-arts-and-culture-mandalay', null::smallint, 'https://culture.gov.mm', 'Public university in Patheingyi for performing arts, visual arts, and cultural study.'),
    ('university-of-technology-yadanabon-cyber-city', 2010::smallint, 'https://utycc.edu.mm', 'Public engineering and information technology university at Yadanabon Cyber City near Pyin Oo Lwin.'),
    ('yezin-agricultural-university', 1924::smallint, 'https://yau.edu.mm', 'Myanmar''s principal public agricultural university in Yezin, Nay Pyi Taw.'),
    ('university-of-veterinary-science-yezin', 1957::smallint, 'https://uvs.edu.mm', 'Myanmar''s specialized public veterinary university in Yezin, Nay Pyi Taw.'),
    ('university-of-forestry-and-environmental-science-yezin', 1923::smallint, 'https://ufes.edu.mm', 'Public university in Yezin for forestry and environmental science.'),
    ('mawlamyine-university', 1953::smallint, 'https://mlmuni.edu.mm', 'Major public arts and sciences university in Mon State with marine science study.'),
    ('taunggyi-university', 1961::smallint, null, 'Major public arts and sciences university serving Shan State.'),
    ('university-of-myitkyina', 1996::smallint, 'https://umkn.edu.mm', 'Public arts and sciences university in Myitkyina, Kachin State.'),
    ('magway-university', 1955::smallint, null, 'Public arts and sciences university in Magway with separate arts and science campus areas.'),
    ('monywa-university', 1952::smallint, 'https://monywauniversity.moe.edu.mm', 'Public arts and sciences university in Monywa, Sagaing Region.'),
    ('meiktila-university', 2001::smallint, 'https://mtluniversity.edu.mm', 'Public arts and sciences university in Meiktila, Mandalay Region.'),
    ('bago-university', 1977::smallint, 'https://bagouni.moe.edu.mm', 'Public arts and sciences university in Bago.'),
    ('university-of-medicine-magway', 2000::smallint, 'https://ummg.gov.mm', 'Public medical university serving Magway Region.'),
    ('university-of-pyay', 1999::smallint, 'https://pyayuniversity.edu.mm', 'Public arts and sciences university serving western Bago Region.'),
    ('hinthada-university', 2001::smallint, 'https://hu.edu.mm', 'Public arts and sciences university in Hinthada offering humanities, sciences, law, and economics study.')
)
update public.universities u
set
  founded_year = coalesce(u.founded_year, c.founded_year),
  website_url = coalesce(u.website_url, c.website_url),
  about = case
    when u.about is null or u.about = 'A quieter, greener campus experience with accessible lecturers.' then c.about
    else u.about
  end,
  data_source_url = case
    when c.website_url is not null
      and (u.data_source_url is null
        or u.data_source_url like 'https://www.unirank.org/%'
        or u.data_source_url like 'https://en.wikipedia.org/%')
      then c.website_url
    else u.data_source_url
  end,
  data_verified_at = '2026-09-01'::timestamptz,
  updated_at = now()
from collected c
where u.slug = c.slug;

with collected_departments(slug, name) as (
  values
    ('yangon-university-of-economics', 'Economics'),
    ('yangon-university-of-economics', 'Applied Economics'),
    ('yangon-university-of-economics', 'Statistics'),
    ('yangon-university-of-economics', 'Commerce'),
    ('yangon-university-of-economics', 'Management Studies'),
    ('university-of-east-yangon', 'Chemistry'),
    ('university-of-east-yangon', 'Physics'),
    ('university-of-east-yangon', 'Mathematics'),
    ('university-of-east-yangon', 'Zoology'),
    ('university-of-east-yangon', 'Botany'),
    ('university-of-east-yangon', 'Geology'),
    ('university-of-east-yangon', 'Industrial Chemistry'),
    ('university-of-medicine-1-yangon', 'Basic Medical Sciences'),
    ('university-of-medicine-1-yangon', 'Clinical Sciences'),
    ('university-of-medicine-2-yangon', 'Medicine'),
    ('university-of-medicine-2-yangon', 'Myanmar'),
    ('university-of-medicine-2-yangon', 'English'),
    ('university-of-foreign-languages-yangon', 'English'),
    ('university-of-foreign-languages-yangon', 'Myanmar'),
    ('university-of-foreign-languages-yangon', 'Chinese'),
    ('university-of-foreign-languages-yangon', 'Japanese'),
    ('university-of-foreign-languages-yangon', 'French'),
    ('university-of-foreign-languages-yangon', 'Korean'),
    ('university-of-foreign-languages-yangon', 'German'),
    ('university-of-foreign-languages-yangon', 'Russian'),
    ('university-of-foreign-languages-yangon', 'Thai'),
    ('university-of-foreign-languages-yangon', 'Linguistics'),
    ('national-university-of-arts-and-culture-yangon', 'Music'),
    ('national-university-of-arts-and-culture-yangon', 'Dramatic Arts'),
    ('national-university-of-arts-and-culture-yangon', 'Painting'),
    ('national-university-of-arts-and-culture-yangon', 'Sculpture'),
    ('national-university-of-arts-and-culture-yangon', 'Cinema and Drama'),
    ('university-of-west-yangon', 'Myanmar'),
    ('university-of-west-yangon', 'English'),
    ('university-of-west-yangon', 'Geography'),
    ('university-of-west-yangon', 'History'),
    ('university-of-west-yangon', 'Philosophy'),
    ('university-of-west-yangon', 'Oriental Studies'),
    ('university-of-west-yangon', 'Geology'),
    ('university-of-west-yangon', 'Botany'),
    ('university-of-west-yangon', 'Chemistry'),
    ('university-of-west-yangon', 'Mathematics'),
    ('mandalay-technological-university', 'Civil Engineering'),
    ('mandalay-technological-university', 'Mechanical Engineering'),
    ('mandalay-technological-university', 'Electronic Engineering'),
    ('mandalay-technological-university', 'Electrical Power Engineering'),
    ('mandalay-technological-university', 'Computer Engineering and Information Technology'),
    ('mandalay-technological-university', 'Mechatronic Engineering'),
    ('mandalay-technological-university', 'Chemical Engineering'),
    ('mandalay-technological-university', 'Nuclear Technology'),
    ('mandalay-technological-university', 'Mining Engineering'),
    ('mandalay-technological-university', 'Architecture'),
    ('mandalay-technological-university', 'Biotechnology'),
    ('university-of-computer-studies-mandalay', 'Software Engineering'),
    ('university-of-computer-studies-mandalay', 'Knowledge Engineering'),
    ('university-of-computer-studies-mandalay', 'High Performance Computing'),
    ('university-of-computer-studies-mandalay', 'Business Information Systems'),
    ('university-of-foreign-languages-mandalay', 'English'),
    ('university-of-foreign-languages-mandalay', 'Chinese'),
    ('university-of-foreign-languages-mandalay', 'Japanese'),
    ('university-of-foreign-languages-mandalay', 'French'),
    ('university-of-foreign-languages-mandalay', 'Korean'),
    ('university-of-foreign-languages-mandalay', 'German'),
    ('university-of-foreign-languages-mandalay', 'Russian'),
    ('university-of-foreign-languages-mandalay', 'Thai'),
    ('university-of-foreign-languages-mandalay', 'Burmese for International Students'),
    ('university-of-traditional-medicine-mandalay', 'Traditional Medicine Pharmacology'),
    ('national-university-of-arts-and-culture-mandalay', 'Music'),
    ('national-university-of-arts-and-culture-mandalay', 'Drama'),
    ('national-university-of-arts-and-culture-mandalay', 'Painting'),
    ('national-university-of-arts-and-culture-mandalay', 'Sculpture'),
    ('national-university-of-arts-and-culture-mandalay', 'Film'),
    ('university-of-technology-yadanabon-cyber-city', 'Information Science and Technology'),
    ('university-of-technology-yadanabon-cyber-city', 'Computer Engineering'),
    ('university-of-technology-yadanabon-cyber-city', 'Precision Engineering'),
    ('yezin-agricultural-university', 'Agriculture'),
    ('yezin-agricultural-university', 'Agronomy'),
    ('yezin-agricultural-university', 'Horticulture'),
    ('yezin-agricultural-university', 'Agricultural Economics'),
    ('university-of-veterinary-science-yezin', 'Anatomy'),
    ('university-of-veterinary-science-yezin', 'Animal Nutrition'),
    ('university-of-veterinary-science-yezin', 'Animal Science'),
    ('university-of-veterinary-science-yezin', 'Wildlife and Aquatic Diseases'),
    ('university-of-veterinary-science-yezin', 'Genetics and Animal Breeding'),
    ('university-of-veterinary-science-yezin', 'Medicine'),
    ('university-of-veterinary-science-yezin', 'Pathology'),
    ('mawlamyine-university', 'Marine Science'),
    ('taunggyi-university', 'Myanmar'),
    ('taunggyi-university', 'English'),
    ('taunggyi-university', 'Geography'),
    ('taunggyi-university', 'History'),
    ('taunggyi-university', 'Philosophy'),
    ('taunggyi-university', 'Psychology'),
    ('taunggyi-university', 'Oriental Studies'),
    ('taunggyi-university', 'Economics'),
    ('taunggyi-university', 'Law'),
    ('taunggyi-university', 'Mathematics'),
    ('taunggyi-university', 'Chemistry'),
    ('taunggyi-university', 'Physics'),
    ('taunggyi-university', 'Zoology'),
    ('taunggyi-university', 'Botany'),
    ('taunggyi-university', 'Geology')
)
insert into public.departments (university_id, name, source_url)
select u.id, cd.name, coalesce(u.website_url, u.data_source_url)
from collected_departments cd
join public.universities u on u.slug = cd.slug
where not exists (
  select 1 from public.departments d
  where d.university_id = u.id and lower(d.name) = lower(cd.name)
);

with collected_programs(slug, name, degree_level) as (
  values
    ('yangon-university-of-economics', 'Bachelor of Commerce (B.Com.)', 'Bachelor'),
    ('yangon-university-of-economics', 'Bachelor of Business Administration (BBA)', 'Bachelor'),
    ('yangon-university-of-economics', 'Bachelor of Economics (BEcon)', 'Bachelor'),
    ('yangon-university-of-economics', 'Bachelor of Statistics (BStat)', 'Bachelor'),
    ('yangon-university-of-economics', 'Bachelor of Public Administration (BPA)', 'Bachelor'),
    ('yangon-university-of-economics', 'Bachelor of Development Studies (BDevS)', 'Bachelor'),
    ('yangon-university-of-economics', 'Master of Business Administration (MBA)', 'Master'),
    ('yangon-university-of-economics', 'Executive Master of Business Administration (EMBA)', 'Master'),
    ('yangon-university-of-economics', 'Master of Banking and Finance (MBF)', 'Master'),
    ('yangon-university-of-economics', 'Master of Marketing Management (MMM)', 'Master'),
    ('yangon-university-of-economics', 'Master of Hospitality and Tourism Management (MHTM)', 'Master'),
    ('yangon-university-of-economics', 'Postgraduate Diploma Programs', 'Diploma'),
    ('yangon-university-of-economics', 'Doctoral Programs', 'Doctorate'),
    ('dagon-university', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('dagon-university', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('dagon-university', 'Master of Arts (MA)', 'Master'),
    ('dagon-university', 'Master of Science (MSc)', 'Master'),
    ('university-of-east-yangon', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('university-of-east-yangon', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('university-of-east-yangon', 'Master of Arts (MA)', 'Master'),
    ('university-of-east-yangon', 'Master of Science (MSc)', 'Master'),
    ('university-of-medicine-1-yangon', 'Bachelor of Medicine, Bachelor of Surgery (MBBS)', 'Bachelor'),
    ('university-of-medicine-1-yangon', 'Master of Medical Science (MMedSc)', 'Master'),
    ('university-of-medicine-1-yangon', 'Doctor of Medical Science (DrMedSc)', 'Doctorate'),
    ('university-of-medicine-1-yangon', 'Doctor of Philosophy (PhD)', 'Doctorate'),
    ('university-of-medicine-1-yangon', 'Postgraduate Medical Diplomas', 'Diploma'),
    ('university-of-medicine-2-yangon', 'Bachelor of Medicine, Bachelor of Surgery (MBBS)', 'Bachelor'),
    ('university-of-medicine-2-yangon', 'Postgraduate Diploma Programs', 'Diploma'),
    ('university-of-medicine-2-yangon', 'Master''s Programs', 'Master'),
    ('university-of-medicine-2-yangon', 'Doctoral Programs', 'Doctorate'),
    ('university-of-dental-medicine-yangon', 'Bachelor of Dental Surgery (BDS)', 'Bachelor'),
    ('university-of-dental-medicine-yangon', 'Master of Dental Surgery (MDS)', 'Master'),
    ('university-of-dental-medicine-yangon', 'Doctor of Philosophy (PhD)', 'Doctorate'),
    ('university-of-nursing-yangon', 'Bachelor of Nursing Science (Generic)', 'Bachelor'),
    ('university-of-nursing-yangon', 'Bachelor of Nursing Science (Bridge)', 'Bachelor'),
    ('university-of-nursing-yangon', 'Master of Nursing Science (MNSc)', 'Master'),
    ('university-of-nursing-yangon', 'Diploma in Dental Nursing', 'Diploma'),
    ('university-of-nursing-yangon', 'Diploma in Eye, Ear, Nose and Throat Nursing', 'Diploma'),
    ('university-of-nursing-yangon', 'Diploma in Mental Health Nursing', 'Diploma'),
    ('university-of-nursing-yangon', 'Diploma in Paediatric Nursing', 'Diploma'),
    ('university-of-nursing-yangon', 'Diploma in Critical Care Nursing', 'Diploma'),
    ('university-of-nursing-yangon', 'Diploma in Orthopaedic Nursing', 'Diploma'),
    ('university-of-pharmacy-yangon', 'Bachelor of Pharmacy (B.Pharm.)', 'Bachelor'),
    ('university-of-pharmacy-yangon', 'Master of Pharmacy (M.Pharm.)', 'Master'),
    ('university-of-public-health-yangon', 'Master of Public Health (MPH)', 'Master'),
    ('university-of-public-health-yangon', 'Doctor of Philosophy in Public Health', 'Doctorate'),
    ('university-of-public-health-yangon', 'Diploma in Medical Science', 'Diploma'),
    ('university-of-public-health-yangon', 'Diploma in Medical Education', 'Diploma'),
    ('university-of-foreign-languages-yangon', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('university-of-foreign-languages-yangon', 'Master of Arts (MA)', 'Master'),
    ('university-of-foreign-languages-yangon', 'Diploma Programs', 'Diploma'),
    ('yangon-university-of-education', 'Bachelor of Education (BEd)', 'Bachelor'),
    ('yangon-university-of-education', 'Master of Education (MEd)', 'Master'),
    ('yangon-university-of-education', 'Doctor of Philosophy (PhD)', 'Doctorate'),
    ('myanmar-aerospace-engineering-university', 'Bachelor of Engineering in Aerospace Engineering', 'Bachelor'),
    ('myanmar-aerospace-engineering-university', 'Postgraduate Diploma in Aerospace Engineering', 'Diploma'),
    ('national-university-of-arts-and-culture-yangon', 'Bachelor of Arts (Four-Year)', 'Bachelor'),
    ('national-university-of-arts-and-culture-yangon', 'Postgraduate Diploma Programs', 'Diploma'),
    ('technological-university-thanlyin', 'Bachelor of Engineering (BE)', 'Bachelor'),
    ('university-of-west-yangon', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('university-of-west-yangon', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('university-of-west-yangon', 'Bachelor of Arts (Honours)', 'Bachelor'),
    ('university-of-west-yangon', 'Bachelor of Science (Honours)', 'Bachelor'),
    ('university-of-west-yangon', 'Master of Arts (MA)', 'Master'),
    ('university-of-west-yangon', 'Master of Science (MSc)', 'Master'),
    ('university-of-west-yangon', 'Master of Research (MRes)', 'Master'),
    ('mandalay-university', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('mandalay-university', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('mandalay-university', 'Master of Arts (MA)', 'Master'),
    ('mandalay-university', 'Master of Science (MSc)', 'Master'),
    ('mandalay-university', 'Doctor of Philosophy (PhD)', 'Doctorate'),
    ('mandalay-university', 'Bachelor of Laws (LLB)', 'Bachelor'),
    ('mandalay-university', 'Master of Laws (LLM)', 'Master'),
    ('mandalay-technological-university', 'Bachelor of Engineering (BE)', 'Bachelor'),
    ('mandalay-technological-university', 'Bachelor of Architecture (BArch)', 'Bachelor'),
    ('mandalay-technological-university', 'Bachelor of Science in Biotechnology', 'Bachelor'),
    ('mandalay-technological-university', 'Master of Engineering (ME)', 'Master'),
    ('mandalay-technological-university', 'Doctor of Philosophy (PhD)', 'Doctorate'),
    ('university-of-computer-studies-mandalay', 'Bachelor of Computer Science (B.C.Sc.)', 'Bachelor'),
    ('university-of-computer-studies-mandalay', 'Master of Computer Science (M.C.Sc.)', 'Master'),
    ('university-of-computer-studies-mandalay', 'Master of Information Science (M.I.Sc.)', 'Master'),
    ('university-of-computer-studies-mandalay', 'Doctor of Philosophy in Information Technology', 'Doctorate'),
    ('university-of-foreign-languages-mandalay', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('university-of-foreign-languages-mandalay', 'Master of Arts (MA)', 'Master'),
    ('university-of-foreign-languages-mandalay', 'Diploma Programs', 'Diploma'),
    ('yadanabon-university', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('yadanabon-university', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('yadanabon-university', 'Master of Arts (MA)', 'Master'),
    ('yadanabon-university', 'Master of Science (MSc)', 'Master'),
    ('university-of-medicine-mandalay', 'Bachelor of Medicine, Bachelor of Surgery (MBBS)', 'Bachelor'),
    ('university-of-medicine-mandalay', 'Master of Medical Science (MMedSc)', 'Master'),
    ('university-of-medicine-mandalay', 'Doctor of Philosophy (PhD)', 'Doctorate'),
    ('university-of-dental-medicine-mandalay', 'Bachelor of Dental Surgery (BDS)', 'Bachelor'),
    ('university-of-dental-medicine-mandalay', 'Master of Dental Surgery (MDS)', 'Master'),
    ('university-of-dental-medicine-mandalay', 'Doctor of Dental Science (Dr.Dent.Sc.)', 'Doctorate'),
    ('university-of-pharmacy-mandalay', 'Bachelor of Pharmacy (B.Pharm.)', 'Bachelor'),
    ('university-of-pharmacy-mandalay', 'Master of Pharmacy (M.Pharm.)', 'Master'),
    ('university-of-nursing-mandalay', 'Bachelor of Nursing Science (B.N.Sc.)', 'Bachelor'),
    ('university-of-traditional-medicine-mandalay', 'Bachelor of Traditional Medicine (B.T.M.)', 'Bachelor'),
    ('university-of-traditional-medicine-mandalay', 'Master of Traditional Medicine (M.T.M.)', 'Master'),
    ('national-university-of-arts-and-culture-mandalay', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('university-of-technology-yadanabon-cyber-city', 'Bachelor of Engineering in Information Science and Technology', 'Bachelor'),
    ('university-of-technology-yadanabon-cyber-city', 'Bachelor of Engineering in Computer Engineering', 'Bachelor'),
    ('university-of-technology-yadanabon-cyber-city', 'Bachelor of Engineering in Electronic Engineering', 'Bachelor'),
    ('university-of-technology-yadanabon-cyber-city', 'Bachelor of Engineering in Mechanical Precision and Automation', 'Bachelor'),
    ('university-of-technology-yadanabon-cyber-city', 'Bachelor of Engineering in Advanced Materials Engineering', 'Bachelor'),
    ('university-of-technology-yadanabon-cyber-city', 'Master of Engineering (ME)', 'Master'),
    ('university-of-technology-yadanabon-cyber-city', 'Doctor of Philosophy in Information Technology', 'Doctorate'),
    ('yezin-agricultural-university', 'Bachelor of Agricultural Science (B.Ag.Sc.)', 'Bachelor'),
    ('yezin-agricultural-university', 'Master of Agricultural Science (M.Agr.Sc.)', 'Master'),
    ('yezin-agricultural-university', 'Doctor of Philosophy (PhD)', 'Doctorate'),
    ('university-of-veterinary-science-yezin', 'Doctor of Veterinary Medicine (DVM)', 'Doctorate'),
    ('university-of-veterinary-science-yezin', 'Bachelor of Animal Science (BASc)', 'Bachelor'),
    ('university-of-veterinary-science-yezin', 'Doctor of Philosophy (PhD)', 'Doctorate'),
    ('university-of-veterinary-science-yezin', 'Master of Philosophy (MPhil)', 'Master'),
    ('university-of-veterinary-science-yezin', 'Master of Veterinary Medicine (MVM)', 'Master'),
    ('university-of-veterinary-science-yezin', 'Master of Veterinary Science (MVSc)', 'Master'),
    ('university-of-forestry-and-environmental-science-yezin', 'Bachelor of Science in Forestry', 'Bachelor'),
    ('university-of-forestry-and-environmental-science-yezin', 'Master of Science (MSc)', 'Master'),
    ('university-of-forestry-and-environmental-science-yezin', 'Doctor of Philosophy (PhD)', 'Doctorate'),
    ('mawlamyine-university', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('mawlamyine-university', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('mawlamyine-university', 'Master of Arts (MA)', 'Master'),
    ('mawlamyine-university', 'Master of Science (MSc)', 'Master'),
    ('taunggyi-university', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('taunggyi-university', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('taunggyi-university', 'Master of Arts (MA)', 'Master'),
    ('taunggyi-university', 'Master of Science (MSc)', 'Master'),
    ('university-of-myitkyina', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('university-of-myitkyina', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('magway-university', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('magway-university', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('magway-university', 'Master of Arts (MA)', 'Master'),
    ('magway-university', 'Master of Science (MSc)', 'Master'),
    ('monywa-university', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('monywa-university', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('monywa-university', 'Master of Arts (MA)', 'Master'),
    ('monywa-university', 'Master of Science (MSc)', 'Master'),
    ('meiktila-university', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('meiktila-university', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('meiktila-university', 'Master of Arts (MA)', 'Master'),
    ('meiktila-university', 'Master of Science (MSc)', 'Master'),
    ('bago-university', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('bago-university', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('university-of-medicine-magway', 'Bachelor of Medicine, Bachelor of Surgery (MBBS)', 'Bachelor'),
    ('university-of-pyay', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('university-of-pyay', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('university-of-pyay', 'Master of Arts (MA)', 'Master'),
    ('university-of-pyay', 'Master of Science (MSc)', 'Master'),
    ('hinthada-university', 'Bachelor of Arts (BA)', 'Bachelor'),
    ('hinthada-university', 'Bachelor of Science (BSc)', 'Bachelor'),
    ('hinthada-university', 'Bachelor of Laws (LLB)', 'Bachelor'),
    ('hinthada-university', 'Bachelor of Economics (BEcon)', 'Bachelor')
)
insert into public.programs (university_id, department_id, name, degree_level, description, source_url)
select u.id, null, cp.name, cp.degree_level,
  'Degree or credential listed in the collected university catalog.',
  coalesce(u.website_url, u.data_source_url)
from collected_programs cp
join public.universities u on u.slug = cp.slug
where not exists (
  select 1 from public.programs p
  where p.university_id = u.id and lower(p.name) = lower(cp.name)
);

with collected_campuses(slug, name, city, address) as (
  values
    ('yangon-university-of-economics', 'Kamayut Campus', 'Yangon', 'Kamayut Township, Yangon'),
    ('yangon-university-of-economics', 'Hlaing Campus', 'Yangon', 'Hlaing Township, Yangon'),
    ('yangon-university-of-economics', 'Ywathagyi Campus', 'Yangon', 'Ywathagyi, Yangon')
)
insert into public.campuses (university_id, name, city, address, source_url)
select u.id, cc.name, cc.city, cc.address, coalesce(u.website_url, u.data_source_url)
from collected_campuses cc
join public.universities u on u.slug = cc.slug
where not exists (
  select 1 from public.campuses c
  where c.university_id = u.id and lower(c.name) = lower(cc.name)
);
