-- Free-licensed Wikimedia Commons cover images curated by
-- scripts/import-university-photos.ts. The URL remains a valid fallback until
-- the one-time `--apply` command copies the 1600 px derivative into the
-- university-media bucket and replaces cover_image_path with a bucket path.

with photo(slug, url, credit, source_url, licence) as (
  values
    ('dagon-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Convo%20Hall%20Dagon.JPG?width=1600', 'Rockrangoon, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Convo_Hall_Dagon.JPG', 'CC BY-SA 3.0'),
    ('hpa-an-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Entrance%20of%20Hpa-an%20University.jpg?width=1600', 'Ninjastrikers, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Entrance_of_Hpa-an_University.jpg', 'CC BY-SA 4.0'),
    ('lashio-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lashio%20University.jpg?width=1600', 'Eliza_Poe, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Lashio_University.jpg', 'CC BY-SA 3.0'),
    ('loikaw-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Loikaw%20University.jpg?width=1600', 'Kantabon, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Loikaw_University.jpg', 'CC BY-SA 4.0'),
    ('magway-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Magway%20University%20Main%20Hall%202.jpg?width=1600', 'Ninjastrikers, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Magway_University_Main_Hall_2.jpg', 'CC BY-SA 4.0'),
    ('mandalay-technological-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Main%20building%2C%20Mandalay%20Technological%20University.jpg?width=1600', 'အောင်စိုးမိုးစိုးမိုး, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Main_building,_Mandalay_Technological_University.jpg', 'CC BY-SA 3.0'),
    ('mandalay-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mandalay%20University%20Main%20Building%203.jpg?width=1600', 'Kantabon, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Mandalay_University_Main_Building_3.jpg', 'CC BY-SA 4.0'),
    ('mawlamyine-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Moulmein%20University%20-%20panoramio%20-%20joinai.jpg?width=1600', 'joinai, CC BY 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Moulmein_University_-_panoramio_-_joinai.jpg', 'CC BY 3.0'),
    ('meiktila-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Meiktila%20University%20(1).jpg?width=1600', 'Tetsuya Kitahata, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Meiktila_University_(1).jpg', 'CC BY-SA 4.0'),
    ('monywa-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20Of%20Monywa%20001.jpg?width=1600', 'Tetsuya Kitahata, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_Of_Monywa_001.jpg', 'CC BY-SA 4.0'),
    ('myanmar-maritime-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/MMU%2001.JPG?width=1600', 'Researcher at Burmese Wikipedia, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:MMU_01.JPG', 'CC BY-SA 3.0'),
    ('myeik-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Main%20Building%20of%20Myeik%20University.png?width=1600', 'Lthar854, CC BY 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Main_Building_of_Myeik_University.png', 'CC BY 4.0'),
    ('university-of-myitkyina', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Myitkyina.jpg?width=1600', 'Lashi Nan Mai Pan, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Myitkyina.jpg', 'CC BY-SA 4.0'),
    ('pakokku-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20pakokku%2Centrance.jpg?width=1600', 'Treeloverboy, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_pakokku,entrance.jpg', 'CC BY-SA 4.0'),
    ('panglong-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Panglong%20University.jpg?width=1600', 'Mokawn, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Panglong_University.jpg', 'CC BY-SA 3.0'),
    ('pathein-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pathein%20University%20(1).jpg?width=1600', 'Tetsuya Kitahata, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Pathein_University_(1).jpg', 'CC BY-SA 4.0'),
    ('pyay-technological-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pyay%20Technological%20University%20(1).jpg?width=1600', 'Tetsuya Kitahata, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Pyay_Technological_University_(1).jpg', 'CC BY-SA 4.0'),
    ('university-of-pyay', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pyay%20University.jpg?width=1600', 'ကိုဆက် (ပြန်/ဆက်), CC0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Pyay_University.jpg', 'CC0'),
    ('shwebo-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Shwebo%20University.jpg?width=1600', 'Ninjastrikers, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Shwebo_University.jpg', 'CC BY-SA 4.0'),
    ('sittway-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Facade%20of%20Sittwe%20(Sittway)%20University%20-%20Sittwe%20-%20Rakhaing%20(Arakan)%20State%20-%20Myanmar%20(Burma)%20(12231918123).jpg?width=1600', 'Adam Jones, CC BY-SA 2.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Facade_of_Sittwe_(Sittway)_University_-_Sittwe_-_Rakhaing_(Arakan)_State_-_Myanmar_(Burma)_(12231918123).jpg', 'CC BY-SA 2.0'),
    ('taunggyi-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Taunggyi%20University.jpg?width=1600', 'Kantabon, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Taunggyi_University.jpg', 'CC BY-SA 4.0'),
    ('technological-university-hmawbi', 'https://commons.wikimedia.org/wiki/Special:FilePath/Technological%20University%2C%20Hmawbi.jpg?width=1600', 'Unknown author, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Technological_University,_Hmawbi.jpg', 'CC BY-SA 4.0'),
    ('technological-university-hpa-an', 'https://commons.wikimedia.org/wiki/Special:FilePath/Technological%20University%2C%20Hpa-An.jpg?width=1600', 'Samurai0001, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Technological_University,_Hpa-An.jpg', 'CC BY-SA 4.0'),
    ('technological-university-loikaw', 'https://commons.wikimedia.org/wiki/Special:FilePath/TU%20Loikaw%20Main%20Building.jpg?width=1600', 'Kantabon, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:TU_Loikaw_Main_Building.jpg', 'CC BY-SA 4.0'),
    ('technological-university-monywa', 'https://commons.wikimedia.org/wiki/Special:FilePath/Monywa%20Tech%20College.JPG?width=1600', 'Wagaung, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Monywa_Tech_College.JPG', 'CC BY-SA 3.0'),
    ('technological-university-pakokku', 'https://commons.wikimedia.org/wiki/Special:FilePath/Technological%20University%20Pakokku.jpg?width=1600', 'MyatThuAung(TU), CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Technological_University_Pakokku.jpg', 'CC BY-SA 4.0'),
    ('technological-university-sittwe', 'https://commons.wikimedia.org/wiki/Special:FilePath/Technological%20University%2C%20Sittwe.jpg?width=1600', 'Henry_Rolling, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Technological_University,_Sittwe.jpg', 'CC BY-SA 4.0'),
    ('technological-university-taunggyi', 'https://commons.wikimedia.org/wiki/Special:FilePath/TU%20Taunggyi.jpg?width=1600', 'Paingpeace, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:TU_Taunggyi.jpg', 'CC BY-SA 4.0'),
    ('technological-university-taungoo', 'https://commons.wikimedia.org/wiki/Special:FilePath/TU%20Toungoo.jpeg?width=1600', 'ခွန်နိုင်ကို, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:TU_Toungoo.jpeg', 'CC BY-SA 4.0'),
    ('university-of-community-health-magway', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20community%20health.jpg?width=1600', 'Ayeminoo, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_community_health.jpg', 'CC BY-SA 4.0'),
    ('university-of-computer-studies-yangon', 'https://commons.wikimedia.org/wiki/Special:FilePath/UCSY%20-%20Hlaing%20Campus.jpg?width=1600', 'NudyGuy, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:UCSY_-_Hlaing_Campus.jpg', 'CC BY-SA 3.0'),
    ('university-of-dental-medicine-mandalay', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Dental%20Medicine%2C%20Mandalay%2C%20Myanmar.jpg?width=1600', 'Ekyaw, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Dental_Medicine,_Mandalay,_Myanmar.jpg', 'CC BY-SA 3.0'),
    ('university-of-foreign-languages-mandalay', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Foreign%20Languages%2C%20Mandalay%2C%20Myanmar.jpg?width=1600', 'Ekyaw, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Foreign_Languages,_Mandalay,_Myanmar.jpg', 'CC BY-SA 3.0'),
    ('university-of-foreign-languages-yangon', 'https://commons.wikimedia.org/wiki/Special:FilePath/Campus%20View%20of%20Yangon%20University%20of%20Foreign%20Languages%20LRC%20and%20NB%20buildings.jpg?width=1600', 'DuwonSoeTun, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Campus_View_of_Yangon_University_of_Foreign_Languages_LRC_and_NB_buildings.jpg', 'CC BY-SA 4.0'),
    ('university-of-medical-technology-mandalay', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mandalay%20University%20of%20Medical%20Technology%201.jpg?width=1600', 'Kantabon, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Mandalay_University_of_Medical_Technology_1.jpg', 'CC BY-SA 4.0'),
    ('university-of-medical-technology-yangon', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Medical%20Technology%20Yangon%20001.jpg?width=1600', 'Tetsuya Kitahata, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Medical_Technology_Yangon_001.jpg', 'CC BY-SA 4.0'),
    ('university-of-medicine-1-yangon', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Medicine%201.jpg?width=1600', 'Paingpeace, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Medicine_1.jpg', 'CC BY-SA 4.0'),
    ('university-of-medicine-2-yangon', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Medicine%202%2C%20Yangon.jpg?width=1600', 'Phyo WP, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Medicine_2,_Yangon.jpg', 'CC BY-SA 3.0'),
    ('university-of-medicine-magway', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Medicine%2C%20Magway.jpg?width=1600', 'Ninjastrikers, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Medicine,_Magway.jpg', 'CC BY-SA 4.0'),
    ('university-of-medicine-mandalay', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mandalay%20Med%20School.JPG?width=1600', 'Wagaung, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Mandalay_Med_School.JPG', 'CC BY-SA 3.0'),
    ('university-of-medicine-taunggyi', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Medicine%20(Taunggyi).jpg?width=1600', 'RightSideStopper, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Medicine_(Taunggyi).jpg', 'CC BY-SA 4.0'),
    ('university-of-nursing-mandalay', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mandalay%20Nursing%20University.jpg?width=1600', 'Kantabon, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Mandalay_Nursing_University.jpg', 'CC BY-SA 4.0'),
    ('university-of-nursing-yangon', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yangon%20Institute%20of%20Nursing.JPG?width=1600', 'Phyo WP, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Yangon_Institute_of_Nursing.JPG', 'CC BY-SA 3.0'),
    ('university-of-pharmacy-mandalay', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Pharmacy%2C%20Mandalay.jpg?width=1600', 'Ninjastrikers, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Pharmacy,_Mandalay.jpg', 'CC BY-SA 4.0'),
    ('university-of-public-health-yangon', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Public%20Health%2C%20Yangon.JPG?width=1600', 'Phyo WP, CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Public_Health,_Yangon.JPG', 'CC BY-SA 3.0'),
    ('university-of-technology-yadanabon-cyber-city', 'https://commons.wikimedia.org/wiki/Special:FilePath/UT%20YCC.jpg?width=1600', 'Paingpeace, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:UT_YCC.jpg', 'CC BY-SA 4.0'),
    ('university-of-yangon', 'https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Yangon.jpg?width=1600', 'Myrmux, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:University_of_Yangon.jpg', 'CC BY-SA 4.0'),
    ('yadanabon-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yadanabon%20University.jpg?width=1600', 'Linnyankha, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Yadanabon_University.jpg', 'CC BY-SA 4.0'),
    ('yangon-technological-university', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yangon%20Technological%20University%2001.jpg?width=1600', 'U Thet Maw, CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Yangon_Technological_University_01.jpg', 'CC BY-SA 4.0')
)
update public.universities u
set cover_image_path = photo.url,
    cover_image_credit = photo.credit,
    cover_image_source_url = photo.source_url,
    cover_image_license = photo.licence,
    updated_at = now()
from photo
where u.slug = photo.slug
  and u.cover_image_path is null;
